### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/THA/quadruple_idx.txt'

### ISSUE THREAD

**Issue by BEILOP** [yuening-lab/MTG#1]

**Comment by BEILOP** [comment]
```
Traceback (most recent call last):
  File "/home/anaconda3/envs/gnn/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/gnn/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2023.13.12001005/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2023.13.12001005/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2023.13.12001005/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2023.13.12001005/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2023.13.12001005/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2023.13.12001005/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/jiaojiaxin/MTG/train.py", line 111, in <module>
    target_rels = json.load(open(f'data/{args.data}/targetRelIds.json'))
  File "/home/jiaojiaxin/MTG/utils/event_data_processing.py", line 6, in generate_data
    with open(quadruples, 'r') as fr:
FileNotFoundError: [Errno 2] No such file or directory: 'data/THA/quadruple_idx.txt'
```

**Comment by hanxiaoxue114** [comment]
Thanks for reporting the problem! Google drive doesn't show all files due to some security setup. We have re-uploaded all files to OneDrive and the new link is provided in the README file. Please check if you are able to get access to all files.
